services:
  db:
    container_name: test_task_db
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql-data:/var/lib/mysql:cached
      - ./logs/db:/var/log/mysql:cached
  auth-generator:
    container_name: test_task_auth_generator
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 30
  currency-service:
    container_name: test_task_currency_service
    build:
      context: currency-service
      dockerfile: Dockerfile
    environment:
      PORT: 3030
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  gateway-service:
    container_name: test_task_gateway_service
    build:
      context: gateway-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AUTH_HOST: auth-generator
      AUTH_PORT: 8080
      CURRENCY_HOST: currency-service
      CURRENCY_PORT: 3030
  pma:
    container_name: test_task_pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"

